### ISSUE TITLE
Try and configure OPcache 

### ISSUE THREAD

**Issue by robinparisi** [agence-webup/laravel-skeleton#10]

**Comment by matthmart** [comment]
To enable OPCache, just add the following lines inside `ops/dockerfiles/app/php.ini`:

```
; OPCache
opcache.enable=1
opcache.memory_consumption=128
opcache.max_accelerated_files=4000
opcache.revalidate_freq = 15
```

But for now, enabling cache impacts both development & production. So we can't do this now because the workflow allowing different configurations between dev & prod is not ready yet.

**Comment by matthmart** [comment]
OPCache is now enabled in production.
