### ISSUE TITLE
Réécrire le cache busting pour hash les images qu'il y a dans la CSS

### ISSUE THREAD

**Issue by TixieSalander** [agence-webup/laravel-skeleton#41]

**Comment by Byrby** [comment]
Il me semble que le cache busting va disparaître ;)

**Comment by robinparisi** [comment]
Non, on va juste changer de méthode. À l'heure actuelle, c'est Laravel qui ajoute un hash au nom du fichier. Du coup, ce hash n'existe pas réellement (dans public on retrouve style.css et non style-378js39.css) et c'est Nginx qui s'occupe de retirer ce hash lors de la requête.

Les moins :

* nécessite l'utilisation d'un plugin Laravel (propre au framework)
* cela nécessite un système de cache pour le cache (parce que le plugin fait un MD5 du fichier, du coup il faut éviter de le faire à chaque requête, donc on cache le résultat, et la màj n'est pas instantanée)
* nécessite une conf côté serveur
* ne fonctionne pas avec d'autres types de projets

Du coup, on va passer sur le système suivant :

* Au moment de la build, Gulp génère le hash pour les ressources (CSS, JS, images, etc)
* Il passe aussi dans le JS et le CSS pour vérifier s'il y'a des url à mettre à jour (ex: un background-image)
* Il génère un rev-manifest.json qui contient une simple table de correspondance entre le fichier source et le fichier distant 
* Un petit helper PHP permet de lire ce fichier et de remplacer la ressource par l'équivalence hachée
